services:
  postgres:
    image: postgres:16
    container_name: cuandollegamimicrobot
    restart: always
    env_file:
      - .env
    ports:
      - '8000:5432'
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: cuandollegamimicrobot-redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  data:
