services:
  postgres:
    image: postgres:16
    container_name: cuandollegamimicrobot
    restart: always
    env_file:
      - .env
    ports:
      - '8000:5432'
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: cuandollegamimicrobot-redis
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command:
      [
        'redis-server',
        '/usr/local/etc/redis/redis.conf',
        '--requirepass',
        '${REDIS_PASSWORD}',
      ]
    env_file:
      - .env

volumes:
  data:
